
name: 'AdventureWorks2022'
version: '1.0.0'

profile: 'AdventureWorks2022'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

vars:
  future-date: '9999-12-31 23:59:59'

models:
  AdventureWorks2022:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: ephemeral
      +schema: intermediate
    marts:
      dims:
        +materialized: table
      facts:
        +materialized: incremental

snapshots:
  AdventureWorks2022:
    +schema: snapshots
    +strategy: timestamp
    +updated_at: ModifiedDate
    +dbt_valid_to_current: CAST('9999-12-31 23:59:59' AS DATETIME)
    +snapshot_meta_column_names:
      dbt_valid_from: valid_from
      dbt_valid_to: valid_to
