version: 2

models:
  - name: dim_product
    columns:
      - name: ProductID
        data_tests:
          - not_null
      - name: ProductKey
          - not_null
          - unique
  - name: dim_date
    columns:
      - name: DateKey
        data_tests:
          - not_null
          - unique
  - name: dim_territory
    columns:
      - name: TerritoryID
        data_tests:
          - not_null
