version: 2

sources:
  - name: Sales
    tables:
      - name: SalesOrderHeader
        tests:
          - not_null:
              column_name: SalesOrderID
          - unique:
              column_name: SalesOrderID
      - name: SalesOrderDetail
        tests:
          - not_null:
              column_name: SalesOrderID
          - relationships:
              column_name: SalesOrderID
              arguments:
                to: source('Sales', 'SalesOrderHeader')
                field: SalesOrderID
          - relationships:
              column_name: ProductID
              arguments:
                to: source('Production', 'Product')
                field: ProductID
      - name: SalesTerritory
        tests:
          - not_null:
              column_name: TerritoryID
          - unique:
              column_name: TerritoryID
  - name: Production
    tables:
      - name: Product
        tests:
          - not_null:
              column_name: ProductID
          - unique:
              column_name: ProductID
          - relationships:
              column_name: ProductSubCategoryID
              arguments:
                to: source('Production', 'ProductSubcategory')
                field: ProductSubCategoryID
      - name: ProductSubcategory
        tests:
          - not_null:
              column_name: ProductSubCategoryID
          - unique:
              column_name: ProductSubCategoryID
          - relationships:
              column_name: ProductCategoryID
              arguments:
                to: source('Production', 'ProductCategory')
                field: ProductCategoryID
