version: 2

models:
  - name: fact_sales
    columns:
      - name: UnitPrice
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              config:
                tags: ['value']
              arguments:
                min_value: 0
                inclusive: true
      - name: OrderQty
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              config:
                tags: ['value']
              arguments:
                min_value: 1
                inclusive: true
      - name: LineTotal
        data_tests:
          - not_null
          - dbt_utils.accepted_range:
              config:
                tags: ['value']
              arguments:
                min_value: 0
                inclusive: true
      - name: OrderDateKey
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_date')
                field: DateKey
      - name: ProductKey
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_product')
                field: ProductKey
      - name: TerritoryKey
        data_tests:
          - relationships:
              arguments:
                to: ref('dim_territory')
                field: TerritoryKey
