version: 2

models:
  - name: dim_product
    columns:
      - name: ProductID
        description: "Unique product identifier"
        tests:
          - not_null
          - unique
  - name: dim_date
    columns:
      - name: DateKey
        tests:
          - not_null
          - unique
  - name: dim_territory
    columns:
      - name: TerritoryID
        tests:
          - relationships:
              to: source('Sales', 'SalesTerritory')
              field: TerritoryID
